In [2]:
import pandas as pd  # shift + enter

In [3]:
import numpy as np

In [4]:
s = pd.Series([1,2,3,4,5])

In [5]:
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
s = pd.Series([3,5,2,6,9])

In [7]:
s

0    3
1    5
2    2
3    6
4    9
dtype: int64

In [9]:
dates = pd.date_range("2013-01-03", periods = 6)

In [10]:
dates

DatetimeIndex(['2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06',
               '2013-01-07', '2013-01-08'],
              dtype='datetime64[ns]', freq='D')

In [11]:
np.random.randn(1,2)

array([[ 1.17517221,  1.12676714]])

In [12]:
np.random.randn(6,2)

array([[ 0.31103518, -0.79162239],
       [-0.33436053,  1.40936926],
       [-0.88609132, -0.67117089],
       [-0.53669606,  0.63262008],
       [-0.43215957,  2.54482758],
       [ 0.89454776,  1.3713508 ]])

In [14]:
np.random.randn(6,4)

array([[-0.23710824,  0.05733533, -0.54248993,  0.08028059],
       [ 0.9893727 , -1.03845359, -0.19769421, -0.66433679],
       [-0.3955803 , -0.42277797,  0.52141094,  1.09637995],
       [-1.07184443, -0.00875924, -0.75023633,  0.3690843 ],
       [-1.13623208, -1.06064546, -0.28782531,  0.41727001],
       [-1.20854147, -0.45451745,  0.91036538, -2.69395589]])

In [18]:
df = pd.DataFrame(np.random.randn(6,4), index = dates, columns=["A","B","C","D"])

In [19]:
df.head(3)

A         B         C         D
2013-01-03 -1.424989  0.398308  1.658517  0.676833
2013-01-04  0.624805  0.890210 -1.571532 -1.768479
2013-01-05  1.466372 -0.316134 -0.889939 -0.324494

In [20]:
df.tail(2)

A         B         C         D
2013-01-07  2.027665  0.425185  0.070017 -1.522503
2013-01-08 -0.151362  0.514758 -0.498818  0.210660

In [21]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [22]:
df.info

<bound method DataFrame.info of                    A         B         C         D
2013-01-03 -1.424989  0.398308  1.658517  0.676833
2013-01-04  0.624805  0.890210 -1.571532 -1.768479
2013-01-05  1.466372 -0.316134 -0.889939 -0.324494
2013-01-06 -1.956405  1.660258  1.009115  0.230114
2013-01-07  2.027665  0.425185  0.070017 -1.522503
2013-01-08 -0.151362  0.514758 -0.498818  0.210660>

In [24]:
df.describe

<bound method NDFrame.describe of                    A         B         C         D
2013-01-03 -1.424989  0.398308  1.658517  0.676833
2013-01-04  0.624805  0.890210 -1.571532 -1.768479
2013-01-05  1.466372 -0.316134 -0.889939 -0.324494
2013-01-06 -1.956405  1.660258  1.009115  0.230114
2013-01-07  2.027665  0.425185  0.070017 -1.522503
2013-01-08 -0.151362  0.514758 -0.498818  0.210660>

In [25]:
df.sort_values(by = "B", ascending = False)

A         B         C         D
2013-01-06 -1.956405  1.660258  1.009115  0.230114
2013-01-04  0.624805  0.890210 -1.571532 -1.768479
2013-01-08 -0.151362  0.514758 -0.498818  0.210660
2013-01-07  2.027665  0.425185  0.070017 -1.522503
2013-01-03 -1.424989  0.398308  1.658517  0.676833
2013-01-05  1.466372 -0.316134 -0.889939 -0.324494

In [27]:
df["A"]

2013-01-03   -1.424989
2013-01-04    0.624805
2013-01-05    1.466372
2013-01-06   -1.956405
2013-01-07    2.027665
2013-01-08   -0.151362
Freq: D, Name: A, dtype: float64

In [28]:
df[0:3]

A         B         C         D
2013-01-03 -1.424989  0.398308  1.658517  0.676833
2013-01-04  0.624805  0.890210 -1.571532 -1.768479
2013-01-05  1.466372 -0.316134 -0.889939 -0.324494

In [29]:
df.index

DatetimeIndex(['2013-01-03', '2013-01-04', '2013-01-05', '2013-01-06',
               '2013-01-07', '2013-01-08'],
              dtype='datetime64[ns]', freq='D')